import {readFile} from 'node:fs/promises';
import {runInNewContext} from 'node:vm';
import assert from 'node:assert/strict';
const contexts = [];
const Module = {canvas: {getContext(kind, attributes) {contexts.push([kind, attributes]); return {};}}};
runInNewContext(await readFile(new URL('../../engine/web/host-pre.js', import.meta.url), 'utf8'), {Module});
Module.canvas.getContext('webgl', {alpha: false, preserveDrawingBuffer: false});
assert.equal(contexts[0][1].preserveDrawingBuffer, true);
assert.equal(contexts[0][1].alpha, false);
Module.canvas.getContext('2d', {alpha: true});
assert.deepEqual(contexts[1], ['2d', {alpha: true}]);
await Module.retromSetPaused(true);
assert.equal(Module.retromPaused, true);
const calls = [];
Module.SDL2 = {audioContext: {suspend: async () => calls.push('suspend'), resume: async () => calls.push('resume')}};
await Module.retromSetPaused(false);
await Module.retromSetPaused(true);
assert.deepEqual(calls, ['resume', 'suspend']);
let woke = false;
Module.retromWake = () => {woke = true;};
Module.retromKeys = [4];
Module.retromStop();
assert.equal(woke, true);
assert.equal(Module.retromStopped, true);
assert.equal(Module.retromKeys.length, 0);
let closed = false;
Module.SDL2.audioContext.close = async () => {closed = true;};
await Module.retromDispose();
assert.equal(closed, true);
